AWSTemplateFormatVersion: '2010-09-09'
Description: Launches a simple EC2 instance with LAMP stack on t2.micro

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-12345678890  # Replace with your desired AMI ID
      InstanceType: t2.micro        # Replace desired instance type
      KeyName: MyKeyPair          # Name of your existing key pair
      SecurityGroupIds:
        - sg-123456789             # Replace with SG ID allowing SSH access
      UserData: !Join
        - - |
          # Install LAMP stack and other basic tools
          sudo yum update -y
          sudo yum install -y httpd mysql php
          sudo systemctl start httpd mysql
          ... # add additional configuration here
        - - LF
      BlockDevices:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8             # Set desired volume size in GB
            VolumeType: gp2

Outputs:
  InstancePublicIp:
    Value: !GetAtt MyInstance.PublicIp
  InstanceId:
    Value: !Ref MyInstance
